# Generated by Django 3.2.5 on 2021-09-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amigos',
            field=models.ManyToManyField(related_name='friends', to='account.User'),
        ),
    ]
